config/routes.rb
Rails.application.routes.draw do
  get 'comments/index'
  get 'comments/new'
  get 'comments/create'
  get 'pages/about'
  get 'pages/landing'
  post '/contact_me' => 'pages#contact_me', as: 'contact_me'
  get 'users/dashboard'
  resources :tranzactions
  resources :phones do
    collection do
      post 'import_phones_data'
      get 'export_phones_data'
    end
  end
  
  resources :listings do
    resources :comments, only: [:index, :new, :create]
    member do
      post 'claim'
    end
  end
  
  get '/auth/:provider/callback'=>'sessions#create'
  get '/signin'=>'sessions#new', :as=>:signin
  get '/signout'=>'sessions#destroy', :as=>:signout
  get '/auth/failure'=>'sessions#failure'
  root 'listings#index'
end

app/models/phone.rb
class Phone < ApplicationRecord
  has_many :phone_tranzactions
  has_many :listings
  has_and_belongs_to_many :tranzactions, through: :phone_tranzactions

  def select_option
   model.split.last.upcase + ':' + capacity + ':' + imei.to_s
   # +color&.to_s + ':' # +' - ' + original_carrier
  end
  
end

app/controllers/phones_controller.rb
class PhonesController < ApplicationController
  load_and_authorize_resource
  before_action :set_phone, only: [:show, :edit, :update, :destroy]

  # GET /phones
  # GET /phones.json
  def index
    @phones = Phone.all
  end

  # GET /phones/1
  # GET /phones/1.json
  def show
    @tranzactions = PhoneTranzaction.where(phone_id: @phone.id).collect(&:tranzaction)
  end

  # GET /phones/new
  def new
    @phone = Phone.new
  end

  # GET /phones/1/edit
  def edit
  end

  # POST /phones
  # POST /phones.json
  def create
    @phone = Phone.new(phone_params)

    respond_to do |format|
      if @phone.save
        format.html { redirect_to @phone, notice: 'Phone was successfully created.' }
        format.json { render :show, status: :created, location: @phone }
      else
        format.html { render :new }
        format.json { render json: @phone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /phones/1
  # PATCH/PUT /phones/1.json
  def update
    respond_to do |format|
      if @phone.update(phone_params)
        format.html { redirect_to @phone, notice: 'Phone was successfully updated.' }
        format.json { render :show, status: :ok, location: @phone }
      else
        format.html { render :edit }
        format.json { render json: @phone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /phones/1
  # DELETE /phones/1.json
  def destroy
    @phone.destroy
    respond_to do |format|
      format.html { redirect_to phones_url, notice: 'Phone was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def import_phones_data
    results = PhoneDataImporter.new.import
    if results == 'file_error'
      flash[:error] = 'CSV Only for now.'
    else
      flash.notice = "#{results[:saved]} saved. \n #{results[:previous]} persisted. #{results[:errors]&.join('')}"
    end
    redirect_to phones_path
  end
  
  def export_phones_data
    format = params[:format]
    service = PhoneDataExporter.new(format)
    path = service.instance_variable_get('@excel_path')
    send_file(path, filename: "phones-backup-#{Time.current}.#{format}")
  end
  
  private
  
  # Use callbacks to share common setup or constraints between actions.
  def set_phone
    @phone = Phone.find(params[:id])
  end
  
  # Never trust parameters from the scary internet, only allow the white list through.
  def phone_params
    params.fetch(:phone, {})
  end
end

app/views/phones/_form.html.erb
<%= form_with model: @phone, html: {id: 'new-phone-form'} do |f| %>
  <div class="form-group">
    <%= f.label :model, class: 'control-label' %>
    <%= f.select :model, options_for_select(phone_models_for_select), {prompt: 'Select One'}, class: 'form-control' %>
  </div>
  <div class="form-group row">
    <div class="col-sm">
      <%= f.label :capacity, class: 'control-label' %>
      <%= f.select :capacity, options_for_select(phone_capacities_for_select), {prompt: 'Select One'}, class: 'form-control' %>
    </div>
    <div class="col-sm">
      <%= f.label :original_carrier, class: 'control-label' %>
      <%= f.select :original_carrier, options_for_select(carriers_for_select), {prompt: 'Select One'}, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group row">
    <div class="col-sm">
      <%= f.label :battery, class:'control_label' %>
      <%= f.number_field :battery, in: 70..100, class: 'form-control' %>
    </div>
    <div class="col-sm">
      <%= f.label :color %>
      <%= f.select :color, options_for_select(colors_for_select), {prompt:'Select one'}, class:'form-control' %>
    </div>
  </div>
<% end %>

app/views/phones/edit.html.erb
<h1>Editing Phone</h1>

<%= render 'form', phone: @phone %>

<%= link_to 'Show', @phone %> |
<%= link_to 'Back', phones_path %>

app/views/phones/index.html.erb
<p id="notice"><%= notice %></p>
<div class="pull-right">

<%= form_with url: import_phones_data_phones_path, html: {style:'display:inline;'} do |f| %>
  <%= f.label :file, class: 'btn' do %>
      <i class="fa fa-download"></i>
    Import
    <%= f.file_field :file, style: 'display: none;' %>
  <% end %>
<% end %>



<!--  <div class="btn-group btn-block" role="group">-->
<!--    <button id="btnGroupDrop1" type="button" class="btn btn-block btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">-->
<!--      Export-->
<!--    </button>-->
<!--    <div class="dropdown-menu" aria-labelledby="btnGroupDrop1">-->
<%#= link_to 'Export CSV - Coming Soon', export_phones_data_phones_path(format: 'csv'), class: 'disabled dropdown-item' %>
<!--    </div>-->
<!--  </div>-->

<%= link_to  export_phones_data_phones_path(format: 'xlsx'), class: 'btn export' do %>
    <i class="fa fa-share"></i>
    Export
  <% end %>
  
  <%= link_to  new_phone_path, class: 'btn btn-secondary' do %>
    <i class="fa fa-plus"></i>
    New Phone
  <% end %>

</div>
<div class="clearfix"></div>
<table class="table" style="margin-top: 20px;">
  
  <thead>
  <tr>
    <th>Model</th>
    <th>IMEI</th>
    <th>Capacity</th>
    <th>Carrier</th>
  </tr>
  </thead>
  
  <tbody>
  <% @phones.each.with_index do |phone, idx| %>
    <tr class="phone-row clickable <%= 'transparent' if idx.even? %>" data-url="<%= phone_path(phone) %>">
      <td><%= phone.model %></td>
      <td><%= phone.imei %></td>
      <td><%= phone.capacity %></td>
      <td><%= phone.original_carrier %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<br>

<script type="text/javascript" charset="utf-8">
  $('.phone-row').on('click', function () {
    window.location = $(this).data('url');
  })
</script>
<style>
  .transparent {
    background-color: #000000;
  }
</style>

app/views/phones/new.html.erb
<%= link_to 'Back', phones_path %>

<h4>New Phone</h4>
<div class="col-sm-4">
  <%= render partial: 'form' %>
</div>

app/views/phones/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_phone_path(@phone) %> |
<%= link_to 'Back', phones_path %>
<hr>
<div class="row">
  <div class="col-sm-4">
      <div class="card" style="background-color:#04878a; border-color:#aaaaaa;">
        <!--  <img class="card-img-top" src="holder.js/100x180/" alt="">-->
        <div class="card-body">
          <h4 class="card-title">Device Information</h4>
          <p class="card-text">
              <strong>Model</strong>
              <kbd><%= @phone.model %></kbd>
          </p>
        </div>
      </div>
    </div>
  </div>

<div class="row">
  <div class="col-sm-4">
      <div class="card" style="background-color:#04878a; border-color:#aaaaaa;">
        <!--  <img class="card-img-top" src="holder.js/100x180/" alt="">-->
        <div class="card-body">
          <h4 class="card-title"><%= @phone.model %></h4>
          <p class="card-text">Text</p>
        </div>
      </div>
    </div>
  </div>


<div class="row">
  <div class="col-xs-12">
    <table class="table table-inverse table-inverse table-responsive">
      <thead class="thead-inverse">
      History
  
      
      <tr>
        <th>ID</th>
        <th>Subtotal/Total</th>
        <th>Buyer Name</th>
        <th>Date</th>
        <th>Status</th>
      </tr>
      </thead>
      <tbody>
          <% @tranzactions.each do |tranz| %>
      <tr>
        <td scope="row"><%= tranz.id %></td>
        <td><%= tranz.subtotal %>/<%= tranz.total %></td>
        <td><%= tranz.buyer_name %></td>
        <td><%= tranz.created_at.to_date %></td>
        <td><%= 'the status' %></td>
      </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>