config/routes.rb
Rails.application.routes.draw do
  get 'comments/index'
  get 'comments/new'
  get 'comments/create'
  get 'pages/about'
  get 'pages/landing'
  post '/contact_me' => 'pages#contact_me', as: 'contact_me'
  get 'users/dashboard'
  resources :tranzactions
  resources :phones do
    collection do
      post 'import_phones_data'
      get 'export_phones_data'
    end
  end
  
  resources :listings do
    resources :comments, only: [:index, :new, :create]
    member do
      post 'claim'
    end
  end
  
  get '/auth/:provider/callback'=>'sessions#create'
  get '/signin'=>'sessions#new', :as=>:signin
  get '/signout'=>'sessions#destroy', :as=>:signout
  get '/auth/failure'=>'sessions#failure'
  root 'listings#index'
end

app/controllers/tranzactions_controller.rb
class TranzactionsController < ApplicationController
  load_and_authorize_resource
  before_action :set_tranzaction, only: [:show, :edit, :update, :destroy]

  # GET /tranzactions
  # GET /tranzactions.json
  def index
    @tranzactions = Tranzaction.all
  end

  # GET /tranzactions/1
  # GET /tranzactions/1.json
  def show
  end

  # GET /tranzactions/new
  def new
    @tranzaction = Tranzaction.new
  end

  # GET /tranzactions/1/edit
  def edit
  end

  # POST /tranzactions
  # POST /tranzactions.json
  def create
    @tranzaction = Tranzaction.new(tranzaction_params)

    respond_to do |format|
      if @tranzaction.save
        format.html { redirect_to @tranzaction, notice: 'Tranzaction was successfully created.' }
        format.json { render :show, status: :created, location: @tranzaction }
      else
        format.html { render :new }
        format.json { render json: @tranzaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tranzactions/1
  # PATCH/PUT /tranzactions/1.json
  def update
    respond_to do |format|
      if @tranzaction.update(tranzaction_params)
        format.html { redirect_to @tranzaction, notice: 'Tranzaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @tranzaction }
      else
        format.html { render :edit }
        format.json { render json: @tranzaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tranzactions/1
  # DELETE /tranzactions/1.json
  def destroy
    @tranzaction.destroy
    respond_to do |format|
      format.html { redirect_to tranzactions_url, notice: 'Tranzaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tranzaction
      @tranzaction = Tranzaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tranzaction_params
      params.fetch(:tranzaction, {})
    end
end

app/helpers/tranzactions_helper.rb
module TranzactionsHelper
end

app/views/tranzactions/_form.html.erb
<%= form_with(model: tranzaction, local: true) do |form| %>
  <% if tranzaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tranzaction.errors.count, "error") %> prohibited this tranzaction from being saved:</h2>

      <ul>
      <% tranzaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tranzactions/edit.html.erb
<h1>Editing Tranzaction</h1>

<%= render 'form', tranzaction: @tranzaction %>

<%= link_to 'Show', @tranzaction %> |
<%= link_to 'Back', tranzactions_path %>

app/views/tranzactions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tranzactions</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tranzactions.each do |tranzaction| %>
      <tr>
        <td><%= link_to 'Show', tranzaction %></td>
        <td><%= link_to 'Edit', edit_tranzaction_path(tranzaction) %></td>
        <td><%= link_to 'Destroy', tranzaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tranzaction', new_tranzaction_path %>

app/views/tranzactions/new.html.erb
<h1>New Tranzaction</h1>

<%= render 'form', tranzaction: @tranzaction %>

<%= link_to 'Back', tranzactions_path %>

app/views/tranzactions/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_tranzaction_path(@tranzaction) %> |
<%= link_to 'Back', tranzactions_path %>