config/routes.rb
Rails.application.routes.draw do
  get 'comments/index'
  get 'comments/new'
  get 'comments/create'
  get 'pages/about'
  get 'pages/landing'
  post '/contact_me' => 'pages#contact_me', as: 'contact_me'
  get 'users/dashboard'
  resources :tranzactions
  resources :phones do
    collection do
      post 'import_phones_data'
      get 'export_phones_data'
    end
  end
  
  resources :listings do
    resources :comments, only: [:index, :new, :create]
    member do
      post 'claim'
    end
  end
  
  get '/auth/:provider/callback'=>'sessions#create'
  get '/signin'=>'sessions#new', :as=>:signin
  get '/signout'=>'sessions#destroy', :as=>:signout
  get '/auth/failure'=>'sessions#failure'
  root 'listings#index'
end

app/views/phone_transactions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Phone Tranzactions</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @phone_tranzactions.each do |phone_tranzaction| %>
      <tr>
        <td><%= link_to 'Show', phone_tranzaction %></td>
        <td><%= link_to 'Edit', edit_phone_tranzaction_path(phone_tranzaction) %></td>
        <td><%= link_to 'Destroy', phone_tranzaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Phone Tranzaction', new_phone_tranzaction_path %>

app/views/phone_transactions/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_phone_tranzaction_path(@phone_tranzaction) %> |
<%= link_to 'Back', phone_tranzactions_path %>