config/routes.rb
Rails.application.routes.draw do
  get 'comments/index'
  get 'comments/new'
  get 'comments/create'
  get 'pages/about'
  get 'pages/landing'
  post '/contact_me' => 'pages#contact_me', as: 'contact_me'
  get 'users/dashboard'
  resources :tranzactions
  resources :phones do
    collection do
      post 'import_phones_data'
      get 'export_phones_data'
    end
  end
  
  resources :listings do
    resources :comments, only: [:index, :new, :create]
    member do
      post 'claim'
    end
  end
  
  get '/auth/:provider/callback'=>'sessions#create'
  get '/signin'=>'sessions#new', :as=>:signin
  get '/signout'=>'sessions#destroy', :as=>:signout
  get '/auth/failure'=>'sessions#failure'
  root 'listings#index'
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 4.0 %>
<div style="display: flex;">
  <% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
      
      <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>" role="alert">
        
        
        <%= msg %>
        <%#= content_tag :div, msg, :id => "flash_#{name}" %>
      </div>
    <% end %>
  <% end %>
</div>


<style>
  .alert {
    margin: auto;
    display: inline-block;
    justify-content: space-around;
    top: 50px;
    left: 40%;
    position: absolute;
    z-index: 100000;
  }
</style>

<script type="text/javascript" charset="utf-8">
  $(function(){
    setTimeout(function(){
      $('.alert').fadeOut('slow')
    }, 6000)
  })
</script>

app/views/layouts/_navigation.html.erb
<div class="logo" style="min-height: 80px;">
  <%= image_tag 'phonebook.png' %>
</div>

<% if user_signed_in? %>
    <a class="btn sidebar-btn">
      <%= current_user.email %>
    </a>

  <%= link_to 'Sign Out', signout_path, class: 'btn sidebar-btn btn-warning' %>

<% else %>
  <%= link_to signin_path, class: 'btn btn-success sidebar-btn' do %>
    <i class="fa fa-google"></i>
    Sign in
  <% end %>

<% end %>



<%= link_to  phones_path, class: ' btn sidebar-btn' do %>
  <i class="fa fa-mobile"></i>
  Phones
<% end %>

<%= link_to  tranzactions_path, class: 'btn sidebar-btn' do %>
    <i class="fa fa-handshake-o"></i>
  Transactions
<% end %>

<%= link_to 'Listings', listings_path, class: 'btn sidebar-btn' %>
<%= link_to 'About', pages_about_path, class: 'btn sidebar-btn' %>

<style>
  .sidebar-btn {
    width: 100%;
    color: white;
    display: block;
  }
    .mr1 {
      margin-right: 1em;
    }
    .mr2 {
      margin-right: 2em;
      
    }
</style>

<script type="text/javascript" charset="utf-8">
  $(function () {
    $('.export').hover(function () {
      $(this).text('XLSX')
    }).on('mouseout', function () {
      $(this).text('Export')
    })
  })
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "The PhoneBook" %></title>
  <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "The Phone Book" %>">
  
  <!--     Fonts and icons     -->
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons"/>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
  
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track'=>'reload' %>
  <!--  <link href="assets///.min.css?v=2.0.6" rel="stylesheet"/>-->
  
  <%= javascript_include_tag 'application', 'data-turbolinks-track'=>'reload' %>
  
  
  <%= csrf_meta_tags %>
</head>
<body>
<!--<header>-->
<!--</header>-->
<div class="container-fluid" >
  <%= render 'layouts/messages' %>
  <div class="row">
    <div class="col-2" >
      <%= render 'layouts/navigation' %>
    </div>
    <div class="col-10" style="border-left: 1px solid #aaaaaa;height: 100vh">
      <main role="main">
        <%= yield %>
      </main>
    </div>
  </div>
</div>
<!--   Core JS Files   -->
<!--<script src="/assets/javascripts/core/jquery.min.js" type="text/javascript"></script>-->
<!--<script src="/assets/javascripts/core/popper.min.js" type="text/javascript"></script>-->
<!--<script src="assets/core/bootstrap-material-design.min.js" type="text/javascript"></script>-->
<!--<script src="assets/plugins/moment.min.js"></script>-->
<!--	Plugin for the Datepicker, full documentation here: https://github.com/Eonasdan/bootstrap-datetimepicker -->
<!--<script src="assets/plugins/bootstrap-datetimepicker.js" type="text/javascript"></script>-->
<!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->
<!--<script src="assets/plugins/nouislider.min.js" type="text/javascript"></script>-->
<!--  Google Maps Plugin  -->
<!--<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>-->
<!-- Place this tag in your head or just before your close body tag. -->
<script async defer src="https://buttons.github.io/buttons.js"></script>
<!-- Control Center for Material Kit: parallax effects, scripts for the example pages etc -->
<!--<script src="assets/material-kit.js?v=2.0.6" type="text/javascript"></script>-->
</body>
</html>